import turtle as t
import math as m
t.shape('turtle')
x=35
def number(a):
    if a==0:
        t.forward(x)
        t.right(90)
        t.forward(2*x)
        t.right(90)
        t.forward(x)
        t.right(90)
        t.forward(2*x)
        t.right(90)
        t.penup()
        t.forward(1.75*x)
        t.pendown()
    elif a==1:
        t.penup()
        t.right(90)
        t.forward(x)
        t.pendown()
        t.left(135)
        t.forward(x*m.sqrt(2))
        t.right(135)
        t.forward(2*x)
        t.left(90+(m.atan(2/0.75))*180/m.pi)
        t.penup()
        t.forward(x*m.sqrt(4+(0.75)**2))
        t.right(180*(m.atan(2/0.75))/m.pi)
        t.pendown()
    elif a==2:
        t.forward(x)
        t.right(90)
        t.forward(x)
        t.right(45)
        t.forward(x*m.sqrt(2))
        t.left(135)
        t.forward(x)
        t.left((m.atan(2/0.75))*180/m.pi)
        t.penup()
        t.forward(x*m.sqrt(4+(0.75)**2))
        t.right(180*(m.atan(2/0.75))/m.pi)
        t.pendown()
    elif a==3:
        t.forward(x)
        t.right(135)
        t.forward(x*m.sqrt(2))
        t.left(135)
        t.forward(x)
        t.right(135)
        t.forward(x*m.sqrt(2))
        t.left(135+(m.atan(2/1.75))*180/m.pi)
        t.penup()
        t.forward(x*m.sqrt(4+(1.75)**2))
        t.right(180*(m.atan(2/1.75))/m.pi)
        t.pendown()
    elif a==4:
        t.right(90)
        t.forward(x)
        t.left(90)
        t.forward(x)
        t.right(90)
        t.forward(x)
        t.left(180)
        t.forward(2*x)
        t.right(90)
        t.penup()
        t.forward(0.75*x)
        t.pendown()
    elif a==5:
        t.penup()
        t.forward(x)
        t.left(180)
        t.pendown()
        t.forward(x)
        t.left(90)
        t.forward(x)
        t.left(90)
        t.forward(x)
        t.right(90)
        t.forward(x)
        t.right(90)
        t.forward(x)
        t.left(180+(m.atan(2/1.75))*180/m.pi)
        t.penup()
        t.forward(x*m.sqrt(4+(1.75)**2))
        t.right(180*(m.atan(2/1.75))/m.pi)
        t.pendown()
    elif a==6:
        t.forward(x)
        t.left(180)
        t.forward(x)
        t.left(90)
        t.forward(2*x)
        t.left(90)
        t.forward(x)
        t.left(90)
        t.forward(x)
        t.left(90)
        t.forward(x)
        t.left(180+(m.atan(1/1.75))*180/m.pi)
        t.penup()
        t.forward(x*m.sqrt(1+(1.75)**2))
        t.right(180*(m.atan(1/1.75))/m.pi)
        t.pendown()
    elif a==7:
        t.forward(x)
        t.right(135)
        t.forward(x*m.sqrt(2))
        t.left(45)
        t.forward(x)
        t.left(90+(m.atan(2/1.75))*180/m.pi)
        t.penup()
        t.forward(x*m.sqrt(4+(1.75)**2))
        t.right(180*(m.atan(2/1.75))/m.pi)
        t.pendown()
    elif a==8:
        for i in range(4):
            t.forward(x)
            t.right(90)
        number(0)
    elif a==9:
        t.penup()
        t.right(45)
        t.forward(x*m.sqrt(2))
        t.pendown()
        t.right(135)
        for i in range(4):
            t.forward(x)
            t.right(90)
        t.left(45)
        t.forward(x*m.sqrt(2))
        t.left(135+(m.atan(2/1.75))*180/m.pi)
        t.penup()
        t.forward(x*m.sqrt(4+(1.75)**2))
        t.right(180*(m.atan(2/1.75))/m.pi)
        t.pendown()
def numbers(*args):
    for n in args:
        number(n)
A=[1,4,1,7,0,0]
numbers(*A)
        
